name: check

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Run Lint
        run: pnpm lint
      - name: Run Type Check
        run: pnpm typecheck
      - name: Run Tests
        run: pnpm test
