name: check

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # v2
        with:
          version: 9
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Run Lint
        run: pnpm lint
      - name: Run Type Check
        run: pnpm typecheck
      - name: Run Build
        run: pnpm build
      - name: Run Tests
        run: pnpm test
