name: deploy-docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # v2
        with:
          version: 9
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Build docs
        run: pnpm --filter @sterashima78/ts-md-docs build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@a753861a5debcf57bf8b404356158c8e1e33150c # v2
        with:
          path: packages/docs/dist
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@de14547edc9944350dc0481aa5b7afb08e75f254 # v2
